services:
  n8n:
    build: ./
    environment:
      - DATABASE_URL=postgres://n8n:n8n@postgres:5432/n8n
      - PORT=5678
    ports:
      - 5678:5678
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
    ports:
      - 5432:5432
    volumes:
      - n8n_database:/var/lib/postgresql/data
volumes:
  n8n_database:
